classes:
  - cluster.common

parameters:
  openldap:
    hostname: localhost
    image: "osixia/openldap:1.1.8"
    ldapadminimage: "tcpcloud/phpldapadmin:0.6.12"
    admin_password: r00tme
    config_password: r00tme
    server_ip: "10.254.33.10"
    admin_ip: "10.254.33.11"
    volumes:
      database: "/srv/volumes/openldap/database"
      config: "/srv/volumes/openldap/config"
    openldapenv:
      - name: HOSTNAME
        value: "ldap01.mcp-drivetrain.local"
      - name: LDAP_ORGANISATION
        value: "mcp-drivetrain"
      - name: LDAP_DOMAIN
        value: "mcp-drivetrain.local"
      - name: LDAP_TLS
        value: "false"
    ldapadminenv:
      - name: PHPLDAPADMIN_LDAP_HOSTS
        value: "#PYTHON2BASH:[{'server': [{'server': [{'tls': False},{'host':'cicd-openldap-server'}]},{'login': [{'bind_id': 'cn=admin,dc=mcp-drivetrain,dc=local'},{'bind_pass': 'r00tme'}]}]}]"
      - name: PHPLDAPADMIN_HTTPS
        value: "false"
      - name: PHPLDAPADMIN_TRUST_PROXY_SSL
        value: "true"
      - name: PHPLDAPADMIN_SERVER_ADMIN
        value: "admin@localhost"
      - name: PHPLDAPADMIN_THEME
        value: mirantis