classes:
  - cluster.k8s-lab
  - component.namespace
  - component.openldap
  - component.jenkins
  - component.gerrit

parameters:
  target_name: cicd-stack
  namespace: cicd
  kapitan:
    vars:
      target: ${target_name}
      namespace: ${namespace}
    compile:
    - output_path: pre-deploy
      input_type: jsonnet
      output_type: yaml
      input_paths:
        - components/namespace/main.jsonnet
    - output_path: manifests
      input_type: jsonnet
      input_paths:
        - components/openldap/main.jsonnet
        - components/gerrit/main.jsonnet
        - components/jenkins/main.jsonnet
      output_type: yaml
    - output_path: scripts
      input_type: jinja2
      input_paths:
        - scripts
    secrets:
      recipients:
        - name: example@kapitan.dev
          fingerprint: D9234C61F58BEB3ED8552A57E28DC07A3CBFAE7C

  openldap:
    instance_name: ${target_name}-openldap
    replicas: 1
    global:
      ldap_domain_org: mcp-drivetrain
    secret:
      data:
        admin_password: r00tme
        config_password: r00tme
    server:
     service:
       loadbalancerip: "172.18.168.100"
    ldapadmin:
      service:
        loadbalancerip: "172.18.168.101"
      deployment:
        env:
          PHPLDAPADMIN_THEME: mirantis

  jenkins:
    instance_name: ${target_name}-jenkins
    replicas: 1
    secret:
      data:
        admin_password: ${openldap:secret:data:admin_password}
    master:
      service:
        loadbalancerip: "172.18.168.102"

  gerrit:
    instance_name: ${target_name}-gerrit
    replicas: 1
    secret:
      data:
        gerrit_db_password: r00tme
        mysql_root_password: r00tme
        admin_password: ${openldap:secret:data:admin_password}
    database:
      service:
        loadbalancerip: "172.18.168.110"
    server:
      service:
        loadbalancerip: "172.18.168.103"
      deployment:
        env:
          AUTH_TYPE: LDAP
          LDAP_SERVER: "ldap://${openldap:server:service:name}"
          LDAP_ACCOUNTPATTERN: 'uid={username}'
          LDAP_ACCOUNTBASE: "ou=people,${openldap:global:ldap_domain}"
          LDAP_GROUPBASE: "ou=groups,${openldap:global:ldap_domain}"
          LDAP_USERNAME: "admin"
          GERRIT_ADMIN_SSH_PUBLIC: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDmE8T+ddAWd5KiSRqFjnKxSZ/drs2TWxWxerjyv6yuNiHf30QaOYOBXP/WzhSX23TEI7CDmYckjt9sFZXSrhxxGzZgxoNlYfcqULdesoelbFjUnsT8Taa7Gq2X90ZF3jtgLZbxl3yL5KSKCnys0XFFvAOiU2HnVWOl0ji8caTWDg75hRe8ir0/qqVQj0mMcvlVRqTCywhFfRWwrt4HEFN+UG/Z17+CX26hZrP4wfWGxs4Wb3PoOk5htdhMkjoemZRX0Y48sol2x9WEQCVxx29LWvbMCrufcPSwIf9j4TVnfsTMHUsXFBfUr52YlWEvMwjGfm9kW1SVL/AX9cryXIZ"
