classes:
  - cluster.k8s-lab
  - component.namespace
  - component.openldap
  - component.jenkins

parameters:
  target_name: cicd-stack
  namespace: cicd
  kapitan:
    vars:
      target: ${target_name}
      namespace: ${namespace}
    compile:
    - output_path: pre-deploy
      input_type: jsonnet
      output_type: yaml
      input_paths:
        - components/namespace/main.jsonnet
    - output_path: manifests
      input_type: jsonnet
      input_paths:
        - applications/cicd_stack.jsonnet
      output_type: yaml
    - output_path: scripts
      input_type: jinja2
      input_paths:
        - scripts
    secrets:
      recipients:
        - name: example@kapitan.dev
          fingerprint: D9234C61F58BEB3ED8552A57E28DC07A3CBFAE7C

  openldap:
    instance_name: ${target_name}-openldap
    replicas: 1

  jenkins:
    instance_name: ${target_name}-jenkins
    replicas: 1

  cicd_stack:
    secrets:
      cicd_secret:
        name: ${target_name}-secret
        admin_password: r00tme
        config_password: r00tme
