classes:
  - cluster.k8s-lab
  - components.namespace
  - component.openldap

parameters:
  target_name: cicd-openldap
  kapitan:
    vars:
      target: ${target_name}
      namespace: ${namespace}
    compile:
    - output_path: pre-deploy
      input_type: jsonnet
      output_type: yaml
      input_paths:
        - components/namespace/main.jsonnet
    - output_path: manifests
      input_type: jsonnet
      input_paths:
        - components/openldap/main.jsonnet
      output_type: yaml
    - output_path: scripts
      input_type: jinja2
      input_paths:
        - scripts
#    - output_path: .
#      output_type: yaml
#      input_type: jinja2
#      input_paths:
#        - docs/openldap/README.md
    secrets:
      recipients:
        - name: example@kapitan.dev
          fingerprint: D9234C61F58BEB3ED8552A57E28DC07A3CBFAE7C
  namespace: cicd

  openldap:
    instance_name: cicd-openldap
    replicas: 1
