classes:
  - cluster.common

parameters:
  openldap:
    hostname: localhost
    global:
      ldap_domain_org: ldap
      ldap_domain_suffix: local
      ldap_domain_name: ${openldap:global:ldap_domain_org}.${openldap:global:ldap_domain_suffix}
      ldap_domain: dc=${openldap:global:ldap_domain_org},dc=${openldap:global:ldap_domain_suffix}
      ldap_hostname: ldap01.${openldap:global:ldap_domain}
      ldap_tls: "false"
    secret:
      name: ${openldap:instance_name}-secret
      data:
        admin_password: changeme
        config_password: changeme
    server:
      deployment:
        name: ${openldap:instance_name}-server
        image:
          registry: "osixia"
          name: openldap
          tag: "1.1.8"
        volumes:
          database:
            type: PersistentVolumeClaim
            path: "/srv/volumes/openldap/database"
            storage: 2Gi
          config:
            type: PersistentVolumeClaim
            path: "/srv/volumes/openldap/config"
            storage: 2Gi
        env:
          HOSTNAME: ${openldap:global:ldap_hostname}
          LDAP_ORGANISATION: ${openldap:global:ldap_domain_org}
          LDAP_DOMAIN: ${openldap:global:ldap_domain_name}
          LDAP_TLS: ${openldap:global:ldap_tls}
      service:
        name: ${openldap:instance_name}-server
        type: LoadBalancer
    ldapadmin:
      deployment:
        name: ${openldap:instance_name}-ldapadmin
        image:
          registry: "tcpcloud"
          name: "phpldapadmin"
          tag: "0.6.12"
        env:
          PHPLDAPADMIN_HTTPS: "false"
          PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
          PHPLDAPADMIN_SERVER_ADMIN: "admin@localhost"
      service:
        name: ${openldap:instance_name}-ldapadmin
        type: LoadBalancer
